name: Tests
on:
  push:
  pull_request:
permissions:
  contents: read
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          version: "0.6.6"
      - run: uv run --no-project --python 3.12 --with certifi --with pytest python -m pytest -q
